# =============================================================================
# VM Automation - Software Catalog Default Data
# =============================================================================
"""
Catalogue complet de logiciels pour la marketplace.
Contient les définitions des logiciels avec leurs configurations.
"""

from typing import Any

# =============================================================================
# RÔLES & FONCTIONNALITÉS WINDOWS SERVER
# =============================================================================
WINDOWS_ROLES = [
    {
        "name": "ad-domain-services",
        "display_name": "Active Directory (AD DS)",
        "description": "Contrôleur de domaine Active Directory pour la gestion des utilisateurs, groupes et politiques.",
        "short_description": "Contrôleur de domaine AD",
        "category": "windows_role",
        "tags": ["active directory", "domain", "ldap", "users", "groups"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "AD-Domain-Services",
        "icon": "Users",
        "is_featured": True,
        "install_time_minutes": 10,
    },
    {
        "name": "dns-server",
        "display_name": "DNS Server",
        "description": "Serveur DNS intégré à Windows Server pour la résolution de noms.",
        "short_description": "Serveur DNS",
        "category": "windows_role",
        "tags": ["dns", "domain", "resolution", "network"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "DNS",
        "icon": "Globe",
        "install_time_minutes": 5,
    },
    {
        "name": "dhcp-server",
        "display_name": "DHCP Server",
        "description": "Serveur DHCP pour l'attribution automatique d'adresses IP.",
        "short_description": "Serveur DHCP",
        "category": "windows_role",
        "tags": ["dhcp", "ip", "network", "address"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "DHCP",
        "icon": "Network",
        "install_time_minutes": 5,
    },
    {
        "name": "hyperv-role",
        "display_name": "Hyper-V",
        "description": "Rôle de virtualisation Hyper-V pour héberger des machines virtuelles.",
        "short_description": "Virtualisation Hyper-V",
        "category": "windows_role",
        "tags": ["hyperv", "virtualization", "vm", "hypervisor"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "Hyper-V",
        "icon": "Server",
        "install_time_minutes": 10,
    },
    {
        "name": "file-server",
        "display_name": "File Server",
        "description": "Rôle serveur de fichiers pour le partage de fichiers en réseau.",
        "short_description": "Serveur de fichiers",
        "category": "windows_role",
        "tags": ["file", "share", "smb", "storage"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "FS-FileServer",
        "icon": "Folder",
        "install_time_minutes": 3,
    },
    {
        "name": "print-server",
        "display_name": "Print Server",
        "description": "Rôle serveur d'impression pour la gestion centralisée des imprimantes.",
        "short_description": "Serveur d'impression",
        "category": "windows_role",
        "tags": ["print", "printer", "spooler"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "Print-Server",
        "icon": "Printer",
        "install_time_minutes": 5,
    },
    {
        "name": "wsus",
        "display_name": "WSUS",
        "description": "Windows Server Update Services pour la gestion centralisée des mises à jour.",
        "short_description": "Serveur de mises à jour",
        "category": "windows_role",
        "tags": ["wsus", "update", "patch", "windows update"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "UpdateServices",
        "icon": "RefreshCw",
        "install_time_minutes": 15,
    },
    {
        "name": "rds-server",
        "display_name": "Remote Desktop Services",
        "description": "Services Bureau à distance pour l'accès distant aux applications et postes de travail.",
        "short_description": "Bureau à distance",
        "category": "windows_role",
        "tags": ["rds", "remote desktop", "terminal", "rdp"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "RDS-RD-Server",
        "icon": "Monitor",
        "install_time_minutes": 10,
    },
    {
        "name": "windows-backup",
        "display_name": "Windows Server Backup",
        "description": "Fonctionnalité de sauvegarde intégrée à Windows Server.",
        "short_description": "Sauvegarde Windows",
        "category": "windows_role",
        "tags": ["backup", "recovery", "restore"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "Windows-Server-Backup",
        "icon": "HardDrive",
        "install_time_minutes": 3,
    },
    {
        "name": "snmp-service",
        "display_name": "SNMP Service",
        "description": "Service SNMP pour la surveillance réseau.",
        "short_description": "Service SNMP",
        "category": "windows_role",
        "tags": ["snmp", "monitoring", "network"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "SNMP-Service",
        "icon": "Activity",
        "install_time_minutes": 2,
    },
    {
        "name": "telnet-client",
        "display_name": "Telnet Client",
        "description": "Client Telnet pour les connexions réseau en mode texte.",
        "short_description": "Client Telnet",
        "category": "windows_role",
        "tags": ["telnet", "network", "client"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "Telnet-Client",
        "icon": "Terminal",
        "install_time_minutes": 1,
    },
    {
        "name": "iis-webserver",
        "display_name": "IIS Web Server",
        "description": "Internet Information Services - Serveur web Microsoft intégré.",
        "short_description": "Serveur web IIS",
        "category": "webserver",
        "tags": ["webserver", "iis", "microsoft", "http", "asp.net"],
        "os_family": "windows",
        "package_manager": "windows_feature",
        "package_id": "Web-Server",
        "icon": "Globe",
        "is_featured": True,
        "install_time_minutes": 5,
        "default_config": {"port": 80},
    },
]

# =============================================================================
# ACCÈS À DISTANCE & SSH
# =============================================================================
REMOTE_ACCESS = [
    {
        "name": "openssh-server",
        "display_name": "OpenSSH Server",
        "description": "Serveur SSH natif Windows pour l'accès distant sécurisé.",
        "short_description": "Serveur SSH natif",
        "category": "remote_access",
        "tags": ["ssh", "remote", "secure", "server"],
        "os_family": "windows",
        "package_manager": "windows_capability",
        "package_id": "OpenSSH.Server~~~~0.0.1.0",
        "icon": "Terminal",
        "is_featured": True,
        "install_time_minutes": 3,
        "default_config": {"port": 22, "auto_start": True},
    },
    {
        "name": "openssh-client",
        "display_name": "OpenSSH Client",
        "description": "Client SSH natif Windows.",
        "short_description": "Client SSH natif",
        "category": "remote_access",
        "tags": ["ssh", "client", "remote"],
        "os_family": "windows",
        "package_manager": "windows_capability",
        "package_id": "OpenSSH.Client~~~~0.0.1.0",
        "icon": "Terminal",
        "install_time_minutes": 1,
    },
    {
        "name": "putty",
        "display_name": "PuTTY",
        "description": "Client SSH et Telnet populaire avec interface graphique.",
        "short_description": "Client SSH/Telnet",
        "category": "remote_access",
        "tags": ["ssh", "telnet", "terminal", "remote"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "putty",
        "icon": "Terminal",
        "website": "https://www.putty.org/",
        "install_time_minutes": 1,
    },
    {
        "name": "winscp",
        "display_name": "WinSCP",
        "description": "Client SFTP/SCP avec interface graphique pour le transfert de fichiers sécurisé.",
        "short_description": "Client SFTP/SCP graphique",
        "category": "remote_access",
        "tags": ["sftp", "scp", "transfer", "file", "ssh"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "winscp",
        "icon": "FolderSync",
        "website": "https://winscp.net/",
        "install_time_minutes": 2,
    },
    {
        "name": "mobaxterm",
        "display_name": "MobaXterm",
        "description": "Terminal avancé multi-protocoles avec serveur X intégré.",
        "short_description": "Terminal multi-protocoles",
        "category": "remote_access",
        "tags": ["ssh", "rdp", "vnc", "terminal", "x11"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "mobaxterm",
        "icon": "Layers",
        "website": "https://mobaxterm.mobatek.net/",
        "install_time_minutes": 3,
    },
    {
        "name": "mremoteng",
        "display_name": "mRemoteNG",
        "description": "Gestionnaire de connexions distantes multi-protocoles.",
        "short_description": "Gestionnaire connexions",
        "category": "remote_access",
        "tags": ["rdp", "ssh", "vnc", "remote", "manager"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "mremoteng",
        "icon": "Monitor",
        "website": "https://mremoteng.org/",
        "install_time_minutes": 2,
    },
]

# =============================================================================
# BASES DE DONNÉES
# =============================================================================
DATABASES = [
    {
        "name": "sql-server-express",
        "display_name": "SQL Server Express",
        "description": "Version gratuite de Microsoft SQL Server pour les applications légères.",
        "short_description": "Base de données SQL Server",
        "category": "database",
        "tags": ["database", "sql", "microsoft", "mssql"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "sql-server-express",
        "icon": "Database",
        "website": "https://www.microsoft.com/sql-server/",
        "is_featured": True,
        "install_time_minutes": 15,
        "default_config": {"enable_tcp": True, "tcp_port": 1433, "mixed_mode": False},
        "config_schema": {
            "fields": [
                {"name": "enable_tcp", "type": "boolean", "label": "Activer TCP/IP", "default": True},
                {"name": "tcp_port", "type": "number", "label": "Port TCP", "default": 1433},
                {"name": "mixed_mode", "type": "boolean", "label": "Authentification mixte", "default": False},
            ]
        },
    },
    {
        "name": "ssms",
        "display_name": "SQL Server Management Studio",
        "description": "Interface d'administration pour SQL Server et Azure SQL Database.",
        "short_description": "Client SSMS",
        "category": "database",
        "tags": ["database", "sql", "microsoft", "management", "ssms"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "sql-server-management-studio",
        "icon": "Database",
        "website": "https://docs.microsoft.com/sql/ssms/",
        "install_time_minutes": 10,
    },
    {
        "name": "mysql",
        "display_name": "MySQL Server",
        "description": "Système de gestion de base de données relationnelle open source.",
        "short_description": "Base de données MySQL",
        "category": "database",
        "tags": ["database", "mysql", "sql", "oracle"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "mysql",
        "icon": "Database",
        "website": "https://www.mysql.com/",
        "install_time_minutes": 10,
        "default_config": {"port": 3306},
    },
    {
        "name": "mysql-workbench",
        "display_name": "MySQL Workbench",
        "description": "Interface graphique officielle pour MySQL.",
        "short_description": "Interface MySQL",
        "category": "database",
        "tags": ["database", "mysql", "gui", "workbench"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "mysql.workbench",
        "icon": "Database",
        "website": "https://www.mysql.com/products/workbench/",
        "install_time_minutes": 5,
    },
    {
        "name": "postgresql",
        "display_name": "PostgreSQL",
        "description": "Base de données relationnelle objet open source avancée.",
        "short_description": "Base de données PostgreSQL",
        "category": "database",
        "tags": ["database", "postgresql", "postgres", "sql"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "postgresql",
        "icon": "Database",
        "website": "https://www.postgresql.org/",
        "install_time_minutes": 10,
        "default_config": {"port": 5432},
    },
    {
        "name": "pgadmin4",
        "display_name": "pgAdmin 4",
        "description": "Interface d'administration pour PostgreSQL.",
        "short_description": "Interface PostgreSQL",
        "category": "database",
        "tags": ["database", "postgresql", "admin", "gui"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "pgadmin4",
        "icon": "Database",
        "website": "https://www.pgadmin.org/",
        "install_time_minutes": 5,
    },
    {
        "name": "mongodb",
        "display_name": "MongoDB",
        "description": "Base de données NoSQL orientée documents.",
        "short_description": "Base de données MongoDB",
        "category": "database",
        "tags": ["database", "mongodb", "nosql", "documents"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "mongodb",
        "icon": "Database",
        "website": "https://www.mongodb.com/",
        "install_time_minutes": 10,
        "default_config": {"port": 27017},
    },
    {
        "name": "redis",
        "display_name": "Redis",
        "description": "Cache et base de données en mémoire haute performance.",
        "short_description": "Cache Redis",
        "category": "database",
        "tags": ["database", "redis", "cache", "memory", "nosql"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "redis-64",
        "icon": "Zap",
        "website": "https://redis.io/",
        "install_time_minutes": 3,
        "default_config": {"port": 6379},
    },
    {
        "name": "mariadb",
        "display_name": "MariaDB",
        "description": "Fork communautaire de MySQL avec compatibilité étendue.",
        "short_description": "Base de données MariaDB",
        "category": "database",
        "tags": ["database", "mariadb", "mysql", "sql"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "mariadb",
        "icon": "Database",
        "website": "https://mariadb.org/",
        "install_time_minutes": 8,
        "default_config": {"port": 3306},
    },
    {
        "name": "sqlite",
        "display_name": "SQLite",
        "description": "Base de données légère sans serveur.",
        "short_description": "Base de données légère",
        "category": "database",
        "tags": ["database", "sqlite", "embedded", "lightweight"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "sqlite",
        "icon": "Database",
        "website": "https://www.sqlite.org/",
        "install_time_minutes": 1,
    },
]

# =============================================================================
# SERVEURS WEB & REVERSE PROXY
# =============================================================================
WEBSERVERS = [
    {
        "name": "urlrewrite",
        "display_name": "URL Rewrite Module",
        "description": "Module IIS pour la réécriture d'URL et les redirections.",
        "short_description": "Module URL Rewrite",
        "category": "webserver",
        "tags": ["iis", "url", "rewrite", "redirect"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "urlrewrite",
        "icon": "Link",
        "website": "https://www.iis.net/downloads/microsoft/url-rewrite",
        "install_time_minutes": 2,
        "dependencies": ["iis-webserver"],
    },
    {
        "name": "nginx",
        "display_name": "nginx",
        "description": "Serveur web et reverse proxy haute performance.",
        "short_description": "Serveur web nginx",
        "category": "webserver",
        "tags": ["webserver", "nginx", "proxy", "http", "reverse proxy"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "nginx",
        "icon": "Server",
        "website": "https://nginx.org/",
        "install_time_minutes": 3,
        "default_config": {"port": 80},
    },
    {
        "name": "apache-httpd",
        "display_name": "Apache HTTP Server",
        "description": "Serveur web Apache, le plus utilisé au monde.",
        "short_description": "Serveur web Apache",
        "category": "webserver",
        "tags": ["webserver", "apache", "http", "httpd"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "apache-httpd",
        "icon": "Server",
        "website": "https://httpd.apache.org/",
        "install_time_minutes": 5,
        "default_config": {"port": 80},
    },
    {
        "name": "traefik",
        "display_name": "Traefik",
        "description": "Reverse proxy et load balancer moderne pour microservices.",
        "short_description": "Reverse proxy moderne",
        "category": "webserver",
        "tags": ["proxy", "traefik", "docker", "kubernetes", "microservices"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "traefik",
        "icon": "Shuffle",
        "website": "https://traefik.io/",
        "install_time_minutes": 3,
    },
    {
        "name": "caddy",
        "display_name": "Caddy",
        "description": "Serveur web avec HTTPS automatique via Let's Encrypt.",
        "short_description": "Serveur web HTTPS auto",
        "category": "webserver",
        "tags": ["webserver", "caddy", "https", "letsencrypt"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "caddy",
        "icon": "Lock",
        "website": "https://caddyserver.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "haproxy",
        "display_name": "HAProxy",
        "description": "Load balancer et proxy haute disponibilité.",
        "short_description": "Load balancer",
        "category": "webserver",
        "tags": ["proxy", "haproxy", "loadbalancer", "ha"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "haproxy",
        "icon": "GitMerge",
        "website": "https://www.haproxy.org/",
        "install_time_minutes": 3,
    },
]

# =============================================================================
# DÉVELOPPEMENT
# =============================================================================
DEVELOPMENT = [
    {
        "name": "git",
        "display_name": "Git",
        "description": "Système de contrôle de version distribué.",
        "short_description": "Contrôle de version",
        "category": "development",
        "tags": ["vcs", "version control", "repository", "github"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "git",
        "icon": "GitBranch",
        "website": "https://git-scm.com/",
        "is_featured": True,
        "install_time_minutes": 3,
    },
    {
        "name": "git-lfs",
        "display_name": "Git LFS",
        "description": "Extension Git pour le stockage de fichiers volumineux.",
        "short_description": "Git Large File Storage",
        "category": "development",
        "tags": ["git", "lfs", "large files"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "git-lfs",
        "icon": "GitBranch",
        "website": "https://git-lfs.github.com/",
        "install_time_minutes": 1,
        "dependencies": ["git"],
    },
    {
        "name": "nodejs-lts",
        "display_name": "Node.js LTS",
        "description": "Runtime JavaScript côté serveur avec npm.",
        "short_description": "Runtime Node.js",
        "category": "runtime",
        "tags": ["javascript", "node", "npm", "runtime", "server"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "nodejs-lts",
        "icon": "Hexagon",
        "website": "https://nodejs.org/",
        "is_featured": True,
        "install_time_minutes": 3,
    },
    {
        "name": "python",
        "display_name": "Python 3",
        "description": "Langage de programmation interprété avec pip.",
        "short_description": "Python 3 + pip",
        "category": "runtime",
        "tags": ["python", "pip", "programming", "scripting"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "python",
        "icon": "Code",
        "website": "https://www.python.org/",
        "is_featured": True,
        "install_time_minutes": 3,
    },
    {
        "name": "python2",
        "display_name": "Python 2.7",
        "description": "Python 2.7 pour les applications legacy.",
        "short_description": "Python 2 (legacy)",
        "category": "runtime",
        "tags": ["python", "legacy", "python2"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "python2",
        "icon": "Code",
        "install_time_minutes": 3,
    },
    {
        "name": "vscode",
        "display_name": "Visual Studio Code",
        "description": "Éditeur de code source puissant avec débogage et extensions.",
        "short_description": "Éditeur VS Code",
        "category": "development",
        "tags": ["ide", "editor", "code", "microsoft", "typescript"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "vscode",
        "icon": "Code",
        "website": "https://code.visualstudio.com/",
        "is_featured": True,
        "install_time_minutes": 5,
    },
    {
        "name": "visualstudio-buildtools",
        "display_name": "Visual Studio Build Tools",
        "description": "Outils de compilation C++/C# sans l'IDE complet.",
        "short_description": "Outils de compilation",
        "category": "development",
        "tags": ["visual studio", "build", "compiler", "c++", "csharp"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "visualstudio2022buildtools",
        "icon": "Hammer",
        "website": "https://visualstudio.microsoft.com/",
        "install_time_minutes": 20,
    },
    {
        "name": "dotnet-sdk",
        "display_name": ".NET SDK",
        "description": "SDK pour le développement d'applications .NET.",
        "short_description": "SDK .NET",
        "category": "runtime",
        "tags": ["dotnet", "csharp", "microsoft", "sdk"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "dotnet-sdk",
        "icon": "Layers",
        "website": "https://dotnet.microsoft.com/",
        "install_time_minutes": 5,
    },
    {
        "name": "dotnet-runtime",
        "display_name": ".NET Runtime",
        "description": "Runtime pour exécuter les applications .NET.",
        "short_description": "Runtime .NET",
        "category": "runtime",
        "tags": ["dotnet", "runtime", "microsoft"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "dotnet-runtime",
        "icon": "Play",
        "website": "https://dotnet.microsoft.com/",
        "install_time_minutes": 3,
    },
    {
        "name": "powershell-core",
        "display_name": "PowerShell 7",
        "description": "PowerShell multi-plateforme nouvelle génération.",
        "short_description": "PowerShell 7",
        "category": "development",
        "tags": ["powershell", "scripting", "automation", "microsoft"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "powershell-core",
        "icon": "Terminal",
        "website": "https://github.com/PowerShell/PowerShell",
        "install_time_minutes": 3,
    },
    {
        "name": "openjdk",
        "display_name": "OpenJDK",
        "description": "Kit de développement Java open source.",
        "short_description": "Java JDK",
        "category": "runtime",
        "tags": ["java", "jdk", "runtime", "programming"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "openjdk",
        "icon": "Coffee",
        "website": "https://openjdk.org/",
        "install_time_minutes": 5,
    },
    {
        "name": "javaruntime",
        "display_name": "Java Runtime",
        "description": "Runtime Java pour exécuter les applications Java.",
        "short_description": "Java JRE",
        "category": "runtime",
        "tags": ["java", "jre", "runtime"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "javaruntime",
        "icon": "Coffee",
        "install_time_minutes": 3,
    },
    {
        "name": "golang",
        "display_name": "Go",
        "description": "Langage de programmation Go de Google.",
        "short_description": "Langage Go",
        "category": "runtime",
        "tags": ["go", "golang", "programming"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "golang",
        "icon": "Code",
        "website": "https://go.dev/",
        "install_time_minutes": 3,
    },
    {
        "name": "rust",
        "display_name": "Rust",
        "description": "Langage de programmation système performant et sûr.",
        "short_description": "Langage Rust",
        "category": "runtime",
        "tags": ["rust", "programming", "system"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "rust",
        "icon": "Code",
        "website": "https://www.rust-lang.org/",
        "install_time_minutes": 5,
    },
    {
        "name": "ruby",
        "display_name": "Ruby",
        "description": "Langage de programmation Ruby.",
        "short_description": "Langage Ruby",
        "category": "runtime",
        "tags": ["ruby", "programming", "rails"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "ruby",
        "icon": "Gem",
        "website": "https://www.ruby-lang.org/",
        "install_time_minutes": 5,
    },
    {
        "name": "php",
        "display_name": "PHP",
        "description": "Langage de script côté serveur pour le web.",
        "short_description": "Langage PHP",
        "category": "runtime",
        "tags": ["php", "web", "scripting"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "php",
        "icon": "Code",
        "website": "https://www.php.net/",
        "install_time_minutes": 3,
    },
    {
        "name": "composer",
        "display_name": "Composer",
        "description": "Gestionnaire de dépendances PHP.",
        "short_description": "Gestionnaire PHP",
        "category": "development",
        "tags": ["php", "composer", "dependency", "package"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "composer",
        "icon": "Package",
        "website": "https://getcomposer.org/",
        "install_time_minutes": 2,
        "dependencies": ["php"],
    },
]

# =============================================================================
# MONITORING & SUPERVISION
# =============================================================================
MONITORING = [
    {
        "name": "zabbix-agent",
        "display_name": "Zabbix Agent",
        "description": "Agent de surveillance pour Zabbix monitoring.",
        "short_description": "Agent Zabbix",
        "category": "monitoring",
        "tags": ["monitoring", "zabbix", "agent", "surveillance"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "zabbix-agent",
        "icon": "Activity",
        "website": "https://www.zabbix.com/",
        "is_featured": True,
        "install_time_minutes": 3,
        "default_config": {"server": "", "hostname": "", "listen_port": 10050},
        "config_schema": {
            "fields": [
                {"name": "server", "type": "string", "label": "Serveur Zabbix", "required": True},
                {"name": "hostname", "type": "string", "label": "Hostname", "required": False},
                {"name": "listen_port", "type": "number", "label": "Port", "default": 10050},
            ]
        },
    },
    {
        "name": "zabbix-agent2",
        "display_name": "Zabbix Agent 2",
        "description": "Nouvelle génération de l'agent Zabbix avec plugins.",
        "short_description": "Agent Zabbix v2",
        "category": "monitoring",
        "tags": ["monitoring", "zabbix", "agent2"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "zabbix-agent2",
        "icon": "Activity",
        "website": "https://www.zabbix.com/",
        "install_time_minutes": 3,
        "default_config": {"server": "", "hostname": ""},
    },
    {
        "name": "prometheus-exporter",
        "display_name": "Prometheus Windows Exporter",
        "description": "Exporter de métriques Windows pour Prometheus.",
        "short_description": "Exporter Prometheus",
        "category": "monitoring",
        "tags": ["monitoring", "prometheus", "metrics", "exporter"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "prometheus-windows-exporter.install",
        "icon": "BarChart",
        "website": "https://prometheus.io/",
        "install_time_minutes": 3,
        "default_config": {"port": 9182},
    },
    {
        "name": "grafana",
        "display_name": "Grafana",
        "description": "Plateforme d'analyse et visualisation de métriques.",
        "short_description": "Dashboards Grafana",
        "category": "monitoring",
        "tags": ["monitoring", "grafana", "dashboard", "visualization"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "grafana",
        "icon": "PieChart",
        "website": "https://grafana.com/",
        "install_time_minutes": 5,
        "default_config": {"port": 3000},
    },
    {
        "name": "telegraf",
        "display_name": "Telegraf",
        "description": "Agent de collecte de métriques pour InfluxDB.",
        "short_description": "Collecteur métriques",
        "category": "monitoring",
        "tags": ["monitoring", "telegraf", "metrics", "influxdb"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "telegraf",
        "icon": "TrendingUp",
        "website": "https://www.influxdata.com/telegraf/",
        "install_time_minutes": 3,
    },
    {
        "name": "datadog-agent",
        "display_name": "Datadog Agent",
        "description": "Agent de monitoring cloud Datadog.",
        "short_description": "Agent Datadog",
        "category": "monitoring",
        "tags": ["monitoring", "datadog", "cloud", "apm"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "datadog-agent",
        "icon": "Dog",
        "website": "https://www.datadoghq.com/",
        "install_time_minutes": 5,
        "default_config": {"api_key": ""},
    },
]

# =============================================================================
# SÉCURITÉ & ANTIVIRUS
# =============================================================================
SECURITY = [
    {
        "name": "wireshark",
        "display_name": "Wireshark",
        "description": "Analyseur de protocole réseau le plus utilisé au monde.",
        "short_description": "Analyseur réseau",
        "category": "security",
        "tags": ["network", "security", "packet", "analyzer", "sniffer"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "wireshark",
        "icon": "Wifi",
        "website": "https://www.wireshark.org/",
        "install_time_minutes": 5,
    },
    {
        "name": "nmap",
        "display_name": "Nmap",
        "description": "Scanner de ports et outil d'exploration réseau.",
        "short_description": "Scanner réseau",
        "category": "security",
        "tags": ["network", "security", "scanner", "ports"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "nmap",
        "icon": "Search",
        "website": "https://nmap.org/",
        "install_time_minutes": 3,
    },
    {
        "name": "sysinternals",
        "display_name": "Sysinternals Suite",
        "description": "Suite d'utilitaires système Microsoft avancés.",
        "short_description": "Outils Sysinternals",
        "category": "security",
        "tags": ["microsoft", "system", "diagnostic", "admin", "procmon"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "sysinternals",
        "icon": "Settings",
        "website": "https://docs.microsoft.com/sysinternals/",
        "is_featured": True,
        "install_time_minutes": 3,
    },
    {
        "name": "procmon",
        "display_name": "Process Monitor",
        "description": "Surveillance en temps réel des processus et du système.",
        "short_description": "Moniteur processus",
        "category": "security",
        "tags": ["process", "monitoring", "sysinternals"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "procmon",
        "icon": "Eye",
        "install_time_minutes": 1,
    },
    {
        "name": "autoruns",
        "display_name": "Autoruns",
        "description": "Gestion complète des programmes au démarrage.",
        "short_description": "Gestion démarrage",
        "category": "security",
        "tags": ["startup", "autorun", "sysinternals"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "autoruns",
        "icon": "PlayCircle",
        "install_time_minutes": 1,
    },
    {
        "name": "malwarebytes",
        "display_name": "Malwarebytes",
        "description": "Anti-malware et protection contre les menaces.",
        "short_description": "Anti-malware",
        "category": "security",
        "tags": ["antivirus", "malware", "security"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "malwarebytes",
        "icon": "Shield",
        "website": "https://www.malwarebytes.com/",
        "install_time_minutes": 5,
    },
    {
        "name": "clamav",
        "display_name": "ClamAV",
        "description": "Antivirus open source.",
        "short_description": "Antivirus open source",
        "category": "security",
        "tags": ["antivirus", "clamav", "opensource"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "clamav",
        "icon": "Shield",
        "website": "https://www.clamav.net/",
        "install_time_minutes": 5,
    },
]

# =============================================================================
# UTILITAIRES SYSTÈME
# =============================================================================
UTILITIES = [
    {
        "name": "7zip",
        "display_name": "7-Zip",
        "description": "Archiveur de fichiers avec haut taux de compression.",
        "short_description": "Archiveur 7-Zip",
        "category": "utilities",
        "tags": ["compression", "archive", "zip", "rar", "7z"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "7zip",
        "icon": "Archive",
        "website": "https://www.7-zip.org/",
        "is_featured": True,
        "install_time_minutes": 2,
    },
    {
        "name": "notepadplusplus",
        "display_name": "Notepad++",
        "description": "Éditeur de texte avancé avec coloration syntaxique.",
        "short_description": "Éditeur Notepad++",
        "category": "utilities",
        "tags": ["editor", "text", "code", "notepad"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "notepadplusplus",
        "icon": "FileText",
        "website": "https://notepad-plus-plus.org/",
        "is_featured": True,
        "install_time_minutes": 2,
    },
    {
        "name": "sublimetext",
        "display_name": "Sublime Text",
        "description": "Éditeur de texte sophistiqué pour code et prose.",
        "short_description": "Éditeur Sublime",
        "category": "utilities",
        "tags": ["editor", "text", "code"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "sublimetext4",
        "icon": "FileText",
        "website": "https://www.sublimetext.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "vim",
        "display_name": "Vim",
        "description": "Éditeur de texte en ligne de commande.",
        "short_description": "Éditeur Vim",
        "category": "utilities",
        "tags": ["editor", "vim", "terminal", "cli"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "vim",
        "icon": "Terminal",
        "website": "https://www.vim.org/",
        "install_time_minutes": 1,
    },
    {
        "name": "totalcommander",
        "display_name": "Total Commander",
        "description": "Gestionnaire de fichiers à deux panneaux.",
        "short_description": "Gestionnaire fichiers",
        "category": "utilities",
        "tags": ["file manager", "explorer", "ftp"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "totalcommander",
        "icon": "FolderOpen",
        "website": "https://www.ghisler.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "everything",
        "display_name": "Everything",
        "description": "Recherche instantanée de fichiers sur Windows.",
        "short_description": "Recherche fichiers",
        "category": "utilities",
        "tags": ["search", "files", "fast"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "everything",
        "icon": "Search",
        "website": "https://www.voidtools.com/",
        "install_time_minutes": 1,
    },
    {
        "name": "treesizefree",
        "display_name": "TreeSize Free",
        "description": "Analyse de l'espace disque avec visualisation.",
        "short_description": "Analyse disque",
        "category": "utilities",
        "tags": ["disk", "space", "analyzer"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "treesizefree",
        "icon": "HardDrive",
        "website": "https://www.jam-software.com/treesize_free",
        "install_time_minutes": 2,
    },
    {
        "name": "hwinfo",
        "display_name": "HWiNFO",
        "description": "Informations détaillées sur le matériel.",
        "short_description": "Infos matériel",
        "category": "utilities",
        "tags": ["hardware", "info", "diagnostic"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "hwinfo",
        "icon": "Cpu",
        "website": "https://www.hwinfo.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "cpu-z",
        "display_name": "CPU-Z",
        "description": "Informations détaillées sur le CPU.",
        "short_description": "Infos CPU",
        "category": "utilities",
        "tags": ["cpu", "hardware", "info"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "cpu-z",
        "icon": "Cpu",
        "website": "https://www.cpuid.com/softwares/cpu-z.html",
        "install_time_minutes": 1,
    },
    {
        "name": "speccy",
        "display_name": "Speccy",
        "description": "Informations système détaillées.",
        "short_description": "Infos système",
        "category": "utilities",
        "tags": ["system", "info", "hardware"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "speccy",
        "icon": "Info",
        "install_time_minutes": 1,
    },
]

# =============================================================================
# NAVIGATEURS WEB
# =============================================================================
BROWSERS = [
    {
        "name": "googlechrome",
        "display_name": "Google Chrome",
        "description": "Navigateur web rapide et sécurisé de Google.",
        "short_description": "Navigateur Chrome",
        "category": "browser",
        "tags": ["browser", "chrome", "google", "web"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "googlechrome",
        "icon": "Chrome",
        "website": "https://www.google.com/chrome/",
        "install_time_minutes": 3,
    },
    {
        "name": "firefox",
        "display_name": "Mozilla Firefox",
        "description": "Navigateur web libre et open source.",
        "short_description": "Navigateur Firefox",
        "category": "browser",
        "tags": ["browser", "firefox", "mozilla", "web"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "firefox",
        "icon": "Globe",
        "website": "https://www.mozilla.org/firefox/",
        "install_time_minutes": 3,
    },
    {
        "name": "microsoft-edge",
        "display_name": "Microsoft Edge",
        "description": "Navigateur Microsoft basé sur Chromium.",
        "short_description": "Navigateur Edge",
        "category": "browser",
        "tags": ["browser", "edge", "microsoft", "chromium"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "microsoft-edge",
        "icon": "Globe",
        "website": "https://www.microsoft.com/edge",
        "install_time_minutes": 3,
    },
    {
        "name": "brave",
        "display_name": "Brave",
        "description": "Navigateur axé sur la vie privée.",
        "short_description": "Navigateur Brave",
        "category": "browser",
        "tags": ["browser", "brave", "privacy", "web"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "brave",
        "icon": "Shield",
        "website": "https://brave.com/",
        "install_time_minutes": 3,
    },
]

# =============================================================================
# CONTAINERS & VIRTUALISATION
# =============================================================================
CONTAINERS = [
    {
        "name": "docker-desktop",
        "display_name": "Docker Desktop",
        "description": "Plateforme complète de containers Docker avec GUI.",
        "short_description": "Docker Desktop",
        "category": "containers",
        "tags": ["docker", "containers", "devops", "virtualization"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "docker-desktop",
        "icon": "Box",
        "website": "https://www.docker.com/",
        "install_time_minutes": 10,
    },
    {
        "name": "docker-cli",
        "display_name": "Docker CLI",
        "description": "Interface en ligne de commande Docker uniquement.",
        "short_description": "Docker CLI",
        "category": "containers",
        "tags": ["docker", "cli", "containers"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "docker-cli",
        "icon": "Terminal",
        "website": "https://www.docker.com/",
        "install_time_minutes": 3,
    },
    {
        "name": "kubectl",
        "display_name": "kubectl",
        "description": "Client CLI officiel pour Kubernetes.",
        "short_description": "Client Kubernetes",
        "category": "containers",
        "tags": ["kubernetes", "k8s", "cli", "containers"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "kubernetes-cli",
        "icon": "Anchor",
        "website": "https://kubernetes.io/",
        "install_time_minutes": 2,
    },
    {
        "name": "helm",
        "display_name": "Helm",
        "description": "Package manager pour Kubernetes.",
        "short_description": "Helm Charts",
        "category": "containers",
        "tags": ["kubernetes", "helm", "charts", "packages"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "kubernetes-helm",
        "icon": "Package",
        "website": "https://helm.sh/",
        "install_time_minutes": 2,
    },
    {
        "name": "minikube",
        "display_name": "Minikube",
        "description": "Kubernetes local pour le développement.",
        "short_description": "K8s local",
        "category": "containers",
        "tags": ["kubernetes", "minikube", "local", "dev"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "minikube",
        "icon": "Anchor",
        "website": "https://minikube.sigs.k8s.io/",
        "install_time_minutes": 5,
    },
    {
        "name": "vagrant",
        "display_name": "Vagrant",
        "description": "Outil de gestion d'environnements de développement virtuels.",
        "short_description": "VM dev",
        "category": "containers",
        "tags": ["vagrant", "vm", "development", "hashicorp"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "vagrant",
        "icon": "Box",
        "website": "https://www.vagrantup.com/",
        "install_time_minutes": 5,
    },
    {
        "name": "virtualbox",
        "display_name": "VirtualBox",
        "description": "Hyperviseur gratuit pour machines virtuelles.",
        "short_description": "Hyperviseur VirtualBox",
        "category": "containers",
        "tags": ["virtualbox", "vm", "hypervisor", "oracle"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "virtualbox",
        "icon": "Server",
        "website": "https://www.virtualbox.org/",
        "install_time_minutes": 10,
    },
]

# =============================================================================
# TRANSFERT DE FICHIERS
# =============================================================================
FILE_TRANSFER = [
    {
        "name": "filezilla",
        "display_name": "FileZilla",
        "description": "Client FTP/SFTP open source.",
        "short_description": "Client FTP",
        "category": "file_transfer",
        "tags": ["ftp", "sftp", "transfer", "client"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "filezilla",
        "icon": "Upload",
        "website": "https://filezilla-project.org/",
        "install_time_minutes": 2,
    },
    {
        "name": "cyberduck",
        "display_name": "Cyberduck",
        "description": "Client cloud storage et FTP.",
        "short_description": "Client cloud/FTP",
        "category": "file_transfer",
        "tags": ["ftp", "cloud", "s3", "transfer"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "cyberduck",
        "icon": "Cloud",
        "website": "https://cyberduck.io/",
        "install_time_minutes": 3,
    },
    {
        "name": "rclone",
        "display_name": "Rclone",
        "description": "Outil de synchronisation cloud multi-fournisseurs.",
        "short_description": "Sync cloud",
        "category": "file_transfer",
        "tags": ["cloud", "sync", "backup", "s3"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "rclone",
        "icon": "CloudOff",
        "website": "https://rclone.org/",
        "install_time_minutes": 2,
    },
    {
        "name": "rsync",
        "display_name": "rsync",
        "description": "Outil de synchronisation de fichiers.",
        "short_description": "Sync fichiers",
        "category": "file_transfer",
        "tags": ["sync", "backup", "files"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "rsync",
        "icon": "RefreshCw",
        "install_time_minutes": 1,
    },
    {
        "name": "curl",
        "display_name": "cURL",
        "description": "Outil de transfert de données en ligne de commande.",
        "short_description": "Transfert CLI",
        "category": "file_transfer",
        "tags": ["http", "transfer", "cli", "api"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "curl",
        "icon": "Download",
        "website": "https://curl.se/",
        "install_time_minutes": 1,
    },
    {
        "name": "wget",
        "display_name": "wget",
        "description": "Outil de téléchargement en ligne de commande.",
        "short_description": "Téléchargement CLI",
        "category": "file_transfer",
        "tags": ["download", "http", "cli"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "wget",
        "icon": "Download",
        "install_time_minutes": 1,
    },
]

# =============================================================================
# RÉSEAU & COMMUNICATION
# =============================================================================
NETWORK = [
    {
        "name": "openvpn",
        "display_name": "OpenVPN",
        "description": "Client et serveur VPN open source.",
        "short_description": "VPN OpenVPN",
        "category": "network",
        "tags": ["vpn", "security", "network", "tunnel"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "openvpn",
        "icon": "Shield",
        "website": "https://openvpn.net/",
        "install_time_minutes": 3,
    },
    {
        "name": "wireguard",
        "display_name": "WireGuard",
        "description": "VPN moderne, simple et performant.",
        "short_description": "VPN WireGuard",
        "category": "network",
        "tags": ["vpn", "wireguard", "security"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "wireguard",
        "icon": "Shield",
        "website": "https://www.wireguard.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "tailscale",
        "display_name": "Tailscale",
        "description": "VPN mesh zero-config basé sur WireGuard.",
        "short_description": "VPN mesh",
        "category": "network",
        "tags": ["vpn", "mesh", "tailscale", "wireguard"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "tailscale",
        "icon": "Link",
        "website": "https://tailscale.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "netcat",
        "display_name": "NetCat",
        "description": "Utilitaire réseau polyvalent.",
        "short_description": "Utilitaire réseau",
        "category": "network",
        "tags": ["network", "netcat", "tcp", "udp"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "netcat",
        "icon": "Activity",
        "install_time_minutes": 1,
    },
    {
        "name": "fiddler",
        "display_name": "Fiddler",
        "description": "Débogueur proxy HTTP pour le web.",
        "short_description": "Débogueur HTTP",
        "category": "network",
        "tags": ["http", "debug", "proxy", "web"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "fiddler",
        "icon": "Globe",
        "website": "https://www.telerik.com/fiddler",
        "install_time_minutes": 3,
    },
    {
        "name": "advanced-ip-scanner",
        "display_name": "Advanced IP Scanner",
        "description": "Scanner réseau gratuit et fiable.",
        "short_description": "Scanner IP",
        "category": "network",
        "tags": ["network", "scanner", "ip", "discovery"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "advanced-ip-scanner",
        "icon": "Search",
        "website": "https://www.advanced-ip-scanner.com/",
        "install_time_minutes": 2,
    },
    {
        "name": "angryip",
        "display_name": "Angry IP Scanner",
        "description": "Scanner IP rapide et léger.",
        "short_description": "Scanner IP rapide",
        "category": "network",
        "tags": ["network", "scanner", "ip"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "angryip",
        "icon": "Search",
        "website": "https://angryip.org/",
        "install_time_minutes": 1,
    },
]

# =============================================================================
# SAUVEGARDE & RÉCUPÉRATION
# =============================================================================
BACKUP = [
    {
        "name": "duplicati",
        "display_name": "Duplicati",
        "description": "Sauvegarde chiffrée vers cloud ou local.",
        "short_description": "Backup chiffré",
        "category": "backup",
        "tags": ["backup", "cloud", "encryption", "restore"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "duplicati",
        "icon": "HardDrive",
        "website": "https://www.duplicati.com/",
        "install_time_minutes": 3,
    },
    {
        "name": "restic",
        "display_name": "Restic",
        "description": "Programme de backup rapide et sécurisé.",
        "short_description": "Backup incrémental",
        "category": "backup",
        "tags": ["backup", "incremental", "deduplication"],
        "os_family": "windows",
        "package_manager": "chocolatey",
        "package_id": "restic",
        "icon": "Archive",
        "website": "https://restic.net/",
        "install_time_minutes": 2,
    },
]

# =============================================================================
# CATALOGUE COMPLET
# =============================================================================
DEFAULT_SOFTWARE_CATALOG: list[dict[str, Any]] = (
    WINDOWS_ROLES
    + REMOTE_ACCESS
    + DATABASES
    + WEBSERVERS
    + DEVELOPMENT
    + MONITORING
    + SECURITY
    + UTILITIES
    + BROWSERS
    + CONTAINERS
    + FILE_TRANSFER
    + NETWORK
    + BACKUP
)

# =============================================================================
# PROFILS PRÉ-DÉFINIS
# =============================================================================
SOFTWARE_PROFILES: dict[str, dict[str, Any]] = {
    "minimal": {
        "name": "minimal",
        "display_name": "Minimal",
        "description": "Configuration minimale avec les outils essentiels.",
        "icon": "Minimize",
        "packages": ["7zip", "notepadplusplus", "googlechrome"],
    },
    "serveur_web": {
        "name": "serveur_web",
        "display_name": "Serveur Web",
        "description": "Configuration pour héberger des sites web avec IIS.",
        "icon": "Globe",
        "packages": ["iis-webserver", "urlrewrite", "php", "mysql", "7zip", "notepadplusplus"],
    },
    "controleur_domaine": {
        "name": "controleur_domaine",
        "display_name": "Contrôleur de Domaine",
        "description": "Configuration Active Directory complète.",
        "icon": "Users",
        "packages": ["ad-domain-services", "dns-server", "dhcp-server", "windows-backup"],
    },
    "developpement": {
        "name": "developpement",
        "display_name": "Développement",
        "description": "Environnement de développement complet.",
        "icon": "Code",
        "packages": ["git", "vscode", "nodejs-lts", "python", "docker-desktop", "7zip", "notepadplusplus"],
    },
    "base_donnees": {
        "name": "base_donnees",
        "display_name": "Base de Données",
        "description": "Serveur de base de données SQL Server.",
        "icon": "Database",
        "packages": ["sql-server-express", "ssms", "7zip", "notepadplusplus"],
    },
    "monitoring": {
        "name": "monitoring",
        "display_name": "Monitoring",
        "description": "Configuration de surveillance et supervision.",
        "icon": "Activity",
        "packages": ["zabbix-agent", "prometheus-exporter", "sysinternals", "7zip", "notepadplusplus"],
    },
    "securite": {
        "name": "securite",
        "display_name": "Sécurité",
        "description": "Outils d'analyse et de sécurité.",
        "icon": "Shield",
        "packages": ["sysinternals", "nmap", "wireshark", "malwarebytes", "autoruns", "procmon"],
    },
    "complet": {
        "name": "complet",
        "display_name": "Complet",
        "description": "Installation complète avec tous les outils essentiels.",
        "icon": "Package",
        "packages": [
            "7zip", "notepadplusplus", "googlechrome",
            "git", "vscode", "python", "nodejs-lts",
            "sysinternals", "zabbix-agent",
            "openssh-server", "putty", "winscp",
        ],
    },
    "file_server": {
        "name": "file_server",
        "display_name": "Serveur de Fichiers",
        "description": "Configuration serveur de fichiers.",
        "icon": "Folder",
        "packages": ["file-server", "windows-backup", "7zip", "notepadplusplus", "everything"],
    },
    "hyperv_host": {
        "name": "hyperv_host",
        "display_name": "Hôte Hyper-V",
        "description": "Configuration pour héberger des VMs.",
        "icon": "Server",
        "packages": ["hyperv-role", "windows-backup", "sysinternals", "7zip", "notepadplusplus"],
    },
}

# =============================================================================
# INFORMATIONS SUR LES CATÉGORIES
# =============================================================================
CATEGORY_INFO: dict[str, dict[str, str]] = {
    "windows_role": {
        "name": "Rôles Windows Server",
        "description": "Fonctionnalités et rôles intégrés à Windows Server",
        "icon": "Server",
        "emoji": "🖥️",
    },
    "remote_access": {
        "name": "Accès à Distance & SSH",
        "description": "Outils pour l'accès distant sécurisé",
        "icon": "Terminal",
        "emoji": "🔐",
    },
    "database": {
        "name": "Bases de Données",
        "description": "Systèmes de gestion de bases de données",
        "icon": "Database",
        "emoji": "🗄️",
    },
    "webserver": {
        "name": "Serveurs Web & Proxy",
        "description": "Serveurs web et reverse proxy",
        "icon": "Globe",
        "emoji": "🌐",
    },
    "development": {
        "name": "Développement",
        "description": "Outils pour les développeurs",
        "icon": "Code",
        "emoji": "👨‍💻",
    },
    "runtime": {
        "name": "Langages & Runtimes",
        "description": "Langages de programmation et environnements d'exécution",
        "icon": "Play",
        "emoji": "⚡",
    },
    "monitoring": {
        "name": "Monitoring & Supervision",
        "description": "Outils de surveillance et métriques",
        "icon": "Activity",
        "emoji": "📊",
    },
    "security": {
        "name": "Sécurité & Antivirus",
        "description": "Outils de sécurité et analyse",
        "icon": "Shield",
        "emoji": "🛡️",
    },
    "utilities": {
        "name": "Utilitaires Système",
        "description": "Outils système essentiels",
        "icon": "Settings",
        "emoji": "🔧",
    },
    "browser": {
        "name": "Navigateurs Web",
        "description": "Navigateurs internet",
        "icon": "Globe",
        "emoji": "🌍",
    },
    "containers": {
        "name": "Containers & Virtualisation",
        "description": "Docker, Kubernetes et outils de virtualisation",
        "icon": "Box",
        "emoji": "📦",
    },
    "file_transfer": {
        "name": "Transfert de Fichiers",
        "description": "Outils FTP, SFTP et synchronisation",
        "icon": "Upload",
        "emoji": "🔄",
    },
    "network": {
        "name": "Réseau & Communication",
        "description": "Outils réseau et VPN",
        "icon": "Wifi",
        "emoji": "📡",
    },
    "backup": {
        "name": "Sauvegarde & Récupération",
        "description": "Outils de backup et restauration",
        "icon": "HardDrive",
        "emoji": "💾",
    },
}


# =============================================================================
# FONCTIONS UTILITAIRES
# =============================================================================
def get_software_by_name(name: str) -> dict[str, Any] | None:
    """Récupère un logiciel par son nom."""
    for software in DEFAULT_SOFTWARE_CATALOG:
        if software["name"] == name:
            return software
    return None


def get_software_by_category(category: str) -> list[dict[str, Any]]:
    """Récupère tous les logiciels d'une catégorie."""
    return [s for s in DEFAULT_SOFTWARE_CATALOG if s.get("category") == category]


def get_profile_packages(profile_name: str) -> list[str]:
    """Récupère la liste des packages d'un profil."""
    profile = SOFTWARE_PROFILES.get(profile_name)
    if profile:
        return profile.get("packages", [])
    return []


def get_featured_software() -> list[dict[str, Any]]:
    """Récupère les logiciels mis en avant."""
    return [s for s in DEFAULT_SOFTWARE_CATALOG if s.get("is_featured")]


def get_all_categories() -> list[str]:
    """Récupère toutes les catégories disponibles."""
    return list(CATEGORY_INFO.keys())


def get_install_command(software: dict[str, Any]) -> str:
    """Génère la commande d'installation pour un logiciel."""
    manager = software.get("package_manager", "chocolatey")
    package_id = software.get("package_id", software["name"])
    
    if manager == "chocolatey":
        return f"choco install {package_id} -y"
    elif manager == "windows_feature":
        return f"Install-WindowsFeature -Name {package_id} -IncludeManagementTools"
    elif manager == "windows_capability":
        return f"Add-WindowsCapability -Online -Name {package_id}"
    elif software.get("install_command_windows"):
        return software["install_command_windows"]
    else:
        return f"choco install {package_id} -y"
